apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-deployment
  namespace: demo-app
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      annotations:
        lastDeploymentAt: {{ now | quote }}  
      labels:
        app: web-deployment
    spec:
      serviceAccountName: default
      containers:
      - name: web-deployment
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - demo-worker
