apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-deployment
  namespace: demo-app
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      annotations:
        lastDeploymentAt: {{ now | quote }}  
      labels:
        app: web-deployment
    spec:
      serviceAccountName: default
      containers:
      - name: web-deployment
        image: 279787105960.dkr.ecr.us-east-1.amazonaws.com/my-python-app-repository:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
