apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: demo-app
spec:
  selector:
    app: web-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
